from pathlib import Path

path = Path('submission/jbi/JBI_main_manuscript_anonymized.md')
text = path.read_text(encoding='utf-8')

replacements = {
'''We audited the environmental model in two stages (Appendix S3). First, ten ecologically motivated interactions were evaluated under the same likelihood, fixed main effects, mesh and five response-blind geographical folds; a second guardrail fitted all 28 possible pairwise products among the eight environmental axes one at a time. Interaction promotion required posterior support plus improved prediction to withheld geography, spatial-block bootstrap support, fold consistency and acceptable VIF. A narrow joint fit resolved any overlapping interaction signals. Second, CHELSA VPD and site water balance tested whether atmospheric demand or integrated water balance added information beyond the primary moisture axis. Alternative spatial specifications compared the stationary field with a coastline-barrier field and tested whether the structural East/West term was needed. A model was not promoted by WAIC alone.''':
'''We audited the environmental model in two stages (Appendix S3). First, ten ecologically motivated interactions were evaluated under the same likelihood, fixed main effects, mesh and five response-blind geographical folds; a second guardrail fitted all 28 possible pairwise products among the eight environmental axes one at a time. Interaction promotion required posterior support plus improved prediction to withheld geography, spatial-block bootstrap support and fold consistency. VIF was treated as a diagnostic rather than a mechanical deletion threshold: values <5 were preferred, values of 5–10 required explicit coefficient, spatial and blocked-transfer stability, and >10 prevented promotion without exceptional justification. A narrow joint fit resolved overlapping interaction signals. Second, CHELSA VPD and site water balance tested whether atmospheric demand or integrated water balance added information beyond the primary moisture axis. Alternative spatial specifications compared the stationary field with a coastline-barrier field and tested whether the structural East/West term was needed. A model was not promoted by WAIC alone.''',

'''Only after candidate identities were fixed did we characterize human context using population, densely inhabited district (DID) metrics, land use and roads. Multiple comparisons within human-feature families used maxT familywise correction. Full event-definition and human-context sensitivities are in Appendix S6. All manuscript-facing analyses, seeds and output provenance are versioned; an anonymized peer-review data/code package will accompany submission.''':
'''Only after candidate identities were fixed did we characterize human context using population, densely inhabited district (DID) proximity, road proximity, built land and forest–human interface context. The final confirmatory family removed near-duplicate composites and placed population at five scales, DID, road, built-up land, forest–human edge, forest cover and mountainness in one global maxT family. Because the local event uses a multiscale four-PC environmental matching basis distinct from the observation-level Broad coefficient model, we also repeated the full 10,000-map analysis with the final eight Broad environmental axes; its caliper was response-blindly calibrated to match primary neighbourhood support before colour or human variables were read. Full propagation and human-context sensitivities are in Appendix S6. All manuscript-facing analyses, seeds and output provenance are versioned; an anonymized peer-review data/code package will accompany submission.''',

'''Human context was suggestive only after these locations had been fixed. The strongest contrasts involved 5-km population rank (directional P=0.0270; maxT familywise P=0.0899) and population-DID alignment (P=0.0230; maxT P=0.0759). We therefore found no robust evidence that the local-departure set requires an additional anthropogenic process or that the candidates have horticultural provenance.''':
'''Human context was suggestive only after these locations had been fixed. Under the predeclared four-PC environmental matching, the strongest variable was 5-km population rank (contrast +0.0531; directional P=0.0305), but it was not supported after global maxT correction across the final 11-variable mechanism family (FWER P=0.2059; P=0.2366 under the direct eight-axis natural model). A response-blind support-matched eight-axis environmental graph replaced two of the 17 candidate identities and strengthened the same 5-km population contrast (+0.0654): global maxT FWER was 0.0463 under the current natural model and 0.0552 under the eight-axis model. Thus the short-scale settlement signal was sensitive to how natural environmental similarity was defined. We found no robust evidence that the local-departure set requires an additional anthropogenic process or that the candidates have horticultural provenance.''',

'''The ornamental use of *C. punctata* nevertheless gives the 17 sites a clear follow-up value. Human-context contrasts were in the expected direction for population-related metrics but remained familywise inconclusive, so the appropriate inference is not anthropogenic origin but prioritization. Vouchers, local planting histories and population-genetic comparisons among candidates, neighbouring wild populations and horticultural material could directly test provenance.''':
'''The ornamental use of *C. punctata* nevertheless gives the 17 sites a clear follow-up value. Short-scale population density is biologically interpretable as a proxy for residential and horticultural opportunity or propagule pressure: horticultural availability can affect escape and establishment in ornamental plants (Dehnen-Schmutz et al., 2007; Davis et al., 2016), and coloured *C. punctata* material has itself been deliberately bred in cultivation (Choi et al., 2012). But this pathway is not uniquely human-biological. Road access and population density can also structure opportunistic recording effort (Mair & Ruete, 2016), and fine-scale shade, irrigation, substrate or thermal conditions can alter anthocyanin-associated colour without any change in ancestry. The matching-sensitive result therefore supports settlement exposure as a provenance hypothesis, not anthropogenic origin. Vouchers, local planting histories and population-genetic comparisons among candidates, neighbouring wild populations and horticultural material could directly test provenance.'''
}

for old, new in replacements.items():
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'Expected one manuscript block, found {count}: {old[:80]!r}')
    text = text.replace(old, new)

refs_marker = '## Data Accessibility Statement'
new_refs = '''\nChoi, M. S., et al. (2012). Breeding of purple flower-colored dwarf ‘Jiknyeo’ from hybridization of *Campanula punctata* Lam. × *Campanula punctata* Lam. var. *rubriflora* Mak. DOI: 10.7235/hort.2012.12015.\n\nDavis, A. J. S., et al. (2016). Accounting for residential propagule pressure improves prediction of urban plant invasion. *Ecosphere*, 7, e01232. https://doi.org/10.1002/ecs2.1232\n\nDehnen-Schmutz, K., Touza, J., Perrings, C., & Williamson, M. (2007). A century of the ornamental plant trade and its impact on invasion success. *Diversity and Distributions*, 13, 527-534. https://doi.org/10.1111/j.1472-4642.2007.00359.x\n\nMair, L., & Ruete, A. (2016). Explaining spatial variation in the recording effort of citizen science data across multiple taxa. *PLoS ONE*, 11, e0147796. https://doi.org/10.1371/journal.pone.0147796\n'''
if 'Dehnen-Schmutz, K.' not in text:
    if refs_marker not in text:
        raise SystemExit('Data Accessibility marker not found')
    text = text.replace(refs_marker, new_refs + '\n' + refs_marker)

path.write_text(text, encoding='utf-8')
print('patched', path)
