# Assemble and validate the canonical analysis-input snapshot.
#
# The snapshot is the versioned, immutable, checksummed boundary that the
# canonical analysis workflow starts from. It carries every input the locked
# publication pipeline consumes and cannot regenerate on a clean runner:
#
#   * the frozen two-part phenotype stage outputs;
#   * the frozen 1-km multiscale cell context;
#   * the MLIT-derived human-landscape rasters and the raw primary-mesh cache
#     that the local-human-context stage re-processes;
#   * the MLIT A16-15 Densely Inhabited District archive the DID stage uses;
#   * the five committed Bombus prediction surfaces;
#   * the WorldPop population raster.
#
# Everything is validated here, before publication, so a canonical run can trust
# it and never needs to contact an external scientific data service.

args <- commandArgs(trailingOnly = TRUE)
source("R/pipeline_support.R")
source("R/reproducibility.R")
hb_require_packages(c("terra", "digest", "jsonlite"))

arg_value <- function(name, default = NULL) hb_arg_value(args, name, default)

results_root <- arg_value("--results-root", "results")
raster_cache <- arg_value(
  "--raster-cache", "reproduction_inputs/public_environment_cache"
)
worldpop_path <- arg_value(
  "--worldpop", file.path(raster_cache, "population_count_Japan_crop.tif")
)
mlit_cache <- arg_value("--mlit-cache", "reproduction_inputs/mlit_l03_2021")
did_cache <- arg_value("--did-cache", "reproduction_inputs/mlit_did_2015")
staging <- arg_value("--staging", "snapshot_staging")
snapshot_id <- arg_value("--snapshot-id", "analysis-input-snapshot-v2")
release_tag <- arg_value("--release-tag", snapshot_id)
asset_name <- arg_value("--asset-name", paste0(snapshot_id, ".tar.gz"))
descriptor_path <- arg_value("--descriptor", "inputs/canonical_snapshot.json")
download_manifest <- arg_value(
  "--download-manifest", "data/processed/raster_download_manifest.csv"
)
processed_manifest <- arg_value(
  "--processed-manifest", "data/processed/raster_manifest.csv"
)
worldpop_url <- arg_value(
  "--worldpop-url",
  "https://data.worldpop.org/GIS/Population/Global_2000_2020_1km/2020/JPN/jpn_ppp_2020_1km_Aggregated.tif"
)
historical_commit <- arg_value(
  "--bombus-commit", "bcceb7c7c909adcb5f7b69721ee5c5921ae90f2e"
)

failures <- character()
note_failure <- function(...) failures <<- c(failures, paste0(...))

# ---------------------------------------------------------------------------
# Established analysis inputs.
#
# Regenerating the phenotype stage and the 1-km cell context from Data_S1.csv
# and the public rasters does not land on the tables the manuscript was computed
# from: row inclusion is decided by complete.cases over the extracted
# environmental covariates, so a coverage difference in any public raster
# changes the analysis population. When the established tables are supplied here
# they are staged instead of the regenerated ones, as archived immutable inputs,
# and the regenerated ones are still validated so the divergence stays visible.
# ---------------------------------------------------------------------------
established_root <- arg_value("--established-inputs", "")
expectations_path <- arg_value(
  "--expectations", "inputs/established_input_expectations.csv"
)
use_established <- nzchar(established_root)
if (use_established && !dir.exists(established_root)) {
  stop(
    "--established-inputs was given but the directory does not exist: ",
    established_root, "\n",
    "  expected: a directory containing ecological_v11_pigmentation_hurdle/ ",
    "and ecological_v15_multiscale_hotspots/ as produced by the published run.\n",
    "  see: docs/established-inputs.md",
    call. = FALSE
  )
}

phenotype_source <- if (use_established) {
  file.path(established_root, "ecological_v11_pigmentation_hurdle")
} else {
  file.path(results_root, "ecological_v11_pigmentation_hurdle")
}
cells_source <- if (use_established) {
  file.path(established_root, "ecological_v15_multiscale_hotspots")
} else {
  file.path(results_root, "ecological_v15_multiscale_hotspots")
}
analysis_input_role <- if (use_established) "archived_input" else "immutable_input"
analysis_input_note <- if (use_established) {
  paste0(
    "established publication artifact supplied from ", established_root,
    "; not regenerated by this run"
  )
} else {
  "regenerated from Data_S1.csv and the pinned public rasters by this run"
}

# ---------------------------------------------------------------------------
# Component declaration.
#
# Each component names a source directory or file, the path it takes inside the
# snapshot, and where it came from. `required` components make publication fail
# when absent; everything is checksummed either way.
# ---------------------------------------------------------------------------
components <- list(
  list(
    id = "phenotype_stage",
    source = phenotype_source,
    target = "analysis_inputs/results/ecological_v11_pigmentation_hurdle",
    role = analysis_input_role,
    provider = paste0(
      "hotarubukuro two-part phenotype stage (01_phenotype); ",
      analysis_input_note
    ),
    url = NA_character_,
    required = TRUE
  ),
  list(
    id = "multiscale_cells",
    source = cells_source,
    target = "analysis_inputs/results/ecological_v15_multiscale_hotspots",
    role = analysis_input_role,
    provider = paste0(
      "hotarubukuro multiscale 1-km cell context stage; ", analysis_input_note
    ),
    url = NA_character_,
    required = TRUE
  ),
  list(
    id = "mlit_human_rasters",
    source = file.path(
      results_root, "public_rasters", "mlit_human_forest_edge_2021"
    ),
    target = "analysis_inputs/results/public_rasters/mlit_human_forest_edge_2021",
    role = "immutable_input",
    provider = "MLIT National Land Numerical Information L03-b 2021, derived 1-km layers",
    url = "https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-L03-b-2021.html",
    required = TRUE
  ),
  list(
    id = "bombus_surfaces",
    source = file.path(results_root, "enmeval_aicc_reselected", "predictions"),
    target = "analysis_inputs/results/enmeval_aicc_reselected/predictions",
    role = "archived_input",
    provider = paste0(
      "committed Bombus prediction surfaces at ", historical_commit,
      "; not regenerated by ENMeval reselection"
    ),
    url = NA_character_,
    required = TRUE
  ),
  list(
    id = "worldpop",
    source = worldpop_path,
    target = "analysis_inputs/rasters/population_count_Japan_crop.tif",
    role = "immutable_input",
    provider = "WorldPop Global 2000-2020 1km, Japan 2020, people per cell",
    url = worldpop_url,
    required = TRUE
  ),
  list(
    id = "mlit_primary_mesh_cache",
    source = mlit_cache,
    target = "analysis_inputs/mlit_l03_2021",
    role = "immutable_input",
    provider = "MLIT National Land Numerical Information L03-b 2021 primary-mesh archives",
    url = "https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-L03-b-2021.html",
    required = TRUE
  ),
  list(
    id = "mlit_did_archive",
    source = did_cache,
    target = "analysis_inputs/mlit_did_2015",
    role = "immutable_input",
    provider = "MLIT National Land Numerical Information A16-15 Densely Inhabited Districts",
    url = "https://nlftp.mlit.go.jp/ksj/gml/data/A16/A16-15/A16-15_GML.zip",
    required = TRUE
  )
)

# ---------------------------------------------------------------------------
# Structural validation of the analysis-ready tables.
# ---------------------------------------------------------------------------
observations_path <- file.path(
  phenotype_source, "analysis_data_pigmentation_hurdle.csv"
)
cells_path <- file.path(cells_source, "multiscale_hotspot_cells_1km.csv")

# The locked column list the downstream stages are built from.
required_observation_columns <- c(
  "observation_id", "exact_site_id", "longitude", "latitude", "x_km", "y_km",
  "pigmented_mixture50", "pigmented_high_confidence", "colour_a", "DOY",
  "bee_ardens", "bee_diversus", "bee_beaticola", "bee_consobrinus",
  "bee_honshuensis"
)
required_cell_columns <- c(
  "exact_site_id", "n_pigmented", "n_observations", "n_independent_sites",
  "longitude", "latitude", "x_km", "y_km", "spatial_fold", "spatial_unit_km",
  "median_year", "median_DOY", "conditional_intensity_median",
  "bombus_fingerprint_common_support",
  "broad50km_pc1", "broad50km_pc2", "within50km_pc1", "within50km_pc2"
)

check_table <- function(path, required_columns, label, unique_site_id = FALSE) {
  if (!file.exists(path)) {
    note_failure("missing ", label, ": ", path)
    return(NULL)
  }
  table <- utils::read.csv(
    path, check.names = FALSE, stringsAsFactors = FALSE
  )
  absent <- setdiff(required_columns, names(table))
  if (length(absent)) {
    note_failure(
      label, " is missing required columns: ",
      paste(absent, collapse = ", ")
    )
  }
  if (!nrow(table)) note_failure(label, " is empty.")
  if (all(c("longitude", "latitude") %in% names(table))) {
    if (anyNA(table$longitude) || anyNA(table$latitude)) {
      note_failure(label, " has missing coordinates.")
    } else if (min(table$longitude) < 122 || max(table$longitude) > 154 ||
               min(table$latitude) < 24 || max(table$latitude) > 46) {
      note_failure(label, " has coordinates outside the Japanese study window.")
    }
  }
  # exact_site_id is the cell key in the cell table, where it must be unique,
  # but a site key in the observation-level phenotype table, where repeats are
  # the normal case of several flowers recorded at one site.
  if (unique_site_id && "exact_site_id" %in% names(table) &&
      anyDuplicated(table$exact_site_id)) {
    note_failure(label, " has duplicate exact_site_id values.")
  }
  table
}

observations <- check_table(
  observations_path, required_observation_columns, "phenotype analysis table"
)
cells <- check_table(
  cells_path, required_cell_columns, "1-km cell table", unique_site_id = TRUE
)
if (!is.null(cells)) {
  if (!all(cells$spatial_unit_km == 1)) {
    note_failure("the cell table is not the 1-km table.")
  }
  if (any(!is.finite(cells$n_observations)) || any(cells$n_observations < 1)) {
    note_failure("every cell must carry at least one observation.")
  }
  if (any(cells$n_pigmented < 0) ||
      any(cells$n_pigmented > cells$n_observations)) {
    note_failure("pigmented counts fall outside [0, n_observations].")
  }
}

# Supplying established tables is only useful if they are the established ones.
# A near-miss — a rerun, a partial export, the reconstruction copied by mistake —
# would otherwise be published under a name that says "as in the manuscript", so
# the counts are checked against the committed expectations before staging.
if (use_established) {
  if (!file.exists(expectations_path)) {
    note_failure(
      "--established-inputs was given but ", expectations_path, " is missing, ",
      "so the supplied tables cannot be confirmed as the published ones."
    )
  } else {
    expectations <- utils::read.csv(
      expectations_path, check.names = FALSE, stringsAsFactors = FALSE
    )
    expected_of <- function(quantity) {
      value <- expectations$expectation[expectations$quantity == quantity]
      if (!length(value)) NA_real_ else as.numeric(value[[1L]])
    }
    if (!is.null(observations)) {
      expected_n <- expected_of("analysis_observations")
      if (!is.na(expected_n) && nrow(observations) != expected_n) {
        note_failure(
          "the supplied phenotype table has ", nrow(observations),
          " rows but the published analysis has ", expected_n,
          ". These are not the established analysis inputs; see ",
          "docs/established-inputs.md."
        )
      }
    }
    measurement_path <- file.path(
      phenotype_source, "pigmentation_measurement_summary.csv"
    )
    if (!file.exists(measurement_path)) {
      note_failure(
        "the supplied phenotype directory has no ",
        "pigmentation_measurement_summary.csv; the whole stage directory is ",
        "needed, not only the analysis table."
      )
    } else {
      measurement <- utils::read.csv(
        measurement_path, check.names = FALSE, stringsAsFactors = FALSE
      )
      for (pair in list(
        c("white_observations", "n_white"),
        c("pigmented_observations", "n_pigmented")
      )) {
        expected_value <- expected_of(pair[[1L]])
        observed_value <- if (pair[[2L]] %in% names(measurement)) {
          as.numeric(measurement[[pair[[2L]]]][[1L]])
        } else {
          NA_real_
        }
        if (!is.na(expected_value) &&
            (is.na(observed_value) || observed_value != expected_value)) {
          note_failure(
            "the supplied measurement summary reports ", pair[[2L]], "=",
            observed_value, " but the published analysis has ", expected_value,
            "."
          )
        }
      }
    }
  }

  # The regenerated tables are not discarded. Whatever this run rebuilt from the
  # public sources is compared against what is being staged, so the snapshot
  # ships with an explicit record of how far the reproducible route lands from
  # the published one.
  regenerated_path <- file.path(
    results_root, "ecological_v11_pigmentation_hurdle",
    "analysis_data_pigmentation_hurdle.csv"
  )
  divergence <- data.frame(
    quantity = "analysis_observations",
    established = if (is.null(observations)) NA_integer_ else nrow(observations),
    regenerated = if (file.exists(regenerated_path)) {
      nrow(utils::read.csv(
        regenerated_path, check.names = FALSE, stringsAsFactors = FALSE
      ))
    } else {
      NA_integer_
    },
    stringsAsFactors = FALSE
  )
  divergence$difference <- divergence$regenerated - divergence$established
  message("[snapshot] established versus regenerated analysis inputs:")
  print(divergence, row.names = FALSE)
}

# ---------------------------------------------------------------------------
# Raster validation: CRS, resolution, extent, and finite values.
# ---------------------------------------------------------------------------
raster_checks <- list()
validate_raster <- function(path, label, expect_epsg = "EPSG:4326",
                            expect_arcsec = FALSE) {
  if (!file.exists(path)) {
    note_failure("missing raster: ", path)
    return(invisible(FALSE))
  }
  layer <- tryCatch(terra::rast(path), error = function(error) NULL)
  if (is.null(layer)) {
    note_failure(label, " could not be opened as a raster.")
    return(invisible(FALSE))
  }
  described <- terra::crs(layer, describe = TRUE)
  code <- paste0(described$authority, ":", described$code)
  resolution <- terra::res(layer)
  extent <- as.vector(terra::ext(layer))
  values_range <- terra::minmax(layer)
  if (!is.na(expect_epsg) && !identical(code, expect_epsg)) {
    note_failure(label, " is on ", code, " rather than ", expect_epsg, ".")
  }
  if (expect_arcsec && abs(resolution[[1L]] - 1 / 120) > 1e-6) {
    note_failure(
      label, " is not on the 30 arc-second grid (resolution ",
      signif(resolution[[1L]], 8), " degrees)."
    )
  }
  if (!all(is.finite(values_range))) {
    note_failure(label, " has no finite values.")
  }
  raster_checks[[length(raster_checks) + 1L]] <<- data.frame(
    layer = label, crs = code, resolution = resolution[[1L]],
    ncol = terra::ncol(layer), nrow = terra::nrow(layer),
    xmin = extent[[1L]], xmax = extent[[2L]],
    ymin = extent[[3L]], ymax = extent[[4L]],
    minimum = values_range[[1L]], maximum = values_range[[2L]],
    stringsAsFactors = FALSE
  )
  invisible(TRUE)
}

validate_raster(worldpop_path, "population_count_Japan_crop.tif")
for (filename in c("mlit_human_forest_edge_1km.tif",
                   "mlit_major_road_distance_1km.tif")) {
  validate_raster(
    file.path(
      results_root, "public_rasters", "mlit_human_forest_edge_2021", filename
    ),
    filename, expect_epsg = NA_character_
  )
}
for (species in c("ardens", "beaticola", "consobrinus", "diversus",
                  "honshuensis")) {
  validate_raster(
    file.path(
      results_root, "enmeval_aicc_reselected", "predictions",
      paste0(species, ".tif")
    ),
    paste0(species, ".tif"), expect_epsg = NA_character_
  )
}

# The DID archive is a zip of shapefiles rather than a raster; check that it is
# a real archive and not an HTML error page saved under a .zip name.
did_shapefiles <- list.files(
  did_cache, pattern = "\\.shp$", recursive = TRUE, full.names = TRUE
)
did_archives <- list.files(
  did_cache, pattern = "\\.zip$", recursive = TRUE, full.names = TRUE
)
if (!length(did_shapefiles) && !length(did_archives)) {
  note_failure(
    "the MLIT DID cache at ", did_cache,
    " contains neither a shapefile nor an archive."
  )
}
for (archive in did_archives) {
  magic <- readBin(archive, what = "raw", n = 2L)
  if (length(magic) != 2L || magic[[1L]] != as.raw(0x50) ||
      magic[[2L]] != as.raw(0x4b)) {
    note_failure(
      basename(archive),
      " is not a zip archive; a provider error page was probably saved."
    )
  }
}

if (length(failures)) {
  stop(
    "Canonical snapshot inputs failed validation:\n  ",
    paste(failures, collapse = "\n  "), call. = FALSE
  )
}

# ---------------------------------------------------------------------------
# Stage the snapshot.
# ---------------------------------------------------------------------------
unlink(staging, recursive = TRUE)
dir.create(file.path(staging, "provenance"), recursive = TRUE)

read_optional_csv <- function(path) {
  if (!file.exists(path)) return(NULL)
  utils::read.csv(path, check.names = FALSE, stringsAsFactors = FALSE)
}
downloads <- read_optional_csv(download_manifest)

staged <- list()
record_staged <- function(relative, absolute, component) {
  staged[[length(staged) + 1L]] <<- data.frame(
    path = relative,
    bytes = as.numeric(file.info(absolute)$size),
    sha256 = rp_sha256(absolute),
    role = component$role,
    component = component$id,
    source = component$provider,
    source_url = component$url,
    retrieved_utc = format(
      file.info(absolute)$mtime, tz = "UTC", usetz = TRUE
    ),
    stringsAsFactors = FALSE
  )
  invisible(NULL)
}

for (component in components) {
  if (!file.exists(component$source)) {
    if (isTRUE(component$required)) {
      stop(
        "Required snapshot component '", component$id, "' is absent: ",
        component$source, call. = FALSE
      )
    }
    message("[snapshot] optional component absent: ", component$id)
    next
  }
  if (dir.exists(component$source)) {
    files <- list.files(component$source, recursive = TRUE, all.files = FALSE)
    files <- files[!grepl("(^|/)logs/", files)]
    if (!length(files)) {
      stop("Snapshot component '", component$id, "' is an empty directory.",
           call. = FALSE)
    }
    for (relative_file in files) {
      source_file <- file.path(component$source, relative_file)
      target_file <- file.path(staging, component$target, relative_file)
      dir.create(dirname(target_file), recursive = TRUE, showWarnings = FALSE)
      if (!file.copy(source_file, target_file, overwrite = TRUE)) {
        stop("Could not stage ", source_file, call. = FALSE)
      }
      record_staged(
        file.path(component$target, relative_file), target_file, component
      )
    }
    message("[snapshot] staged ", length(files), " files for ", component$id)
  } else {
    target_file <- file.path(staging, component$target)
    dir.create(dirname(target_file), recursive = TRUE, showWarnings = FALSE)
    if (!file.copy(component$source, target_file, overwrite = TRUE)) {
      stop("Could not stage ", component$source, call. = FALSE)
    }
    record_staged(component$target, target_file, component)
    message("[snapshot] staged ", component$id)
  }
}

for (path in c(download_manifest, processed_manifest)) {
  if (file.exists(path)) {
    file.copy(
      path, file.path(staging, "provenance", basename(path)), overwrite = TRUE
    )
  }
}
if (length(raster_checks)) {
  rp_write_csv_atomic(
    do.call(rbind, raster_checks),
    file.path(staging, "provenance", "raster_validation.csv")
  )
}

manifest <- do.call(rbind, staged)
manifest <- manifest[order(manifest$path), , drop = FALSE]
rownames(manifest) <- NULL
rp_write_csv_atomic(manifest, file.path(staging, "SNAPSHOT_MANIFEST.csv"))

# The external-source manifest records where each component came from, with the
# retrieval detail the raster download manifest captured where it applies.
external <- data.frame(
  component = vapply(components, `[[`, character(1), "id"),
  role = vapply(components, `[[`, character(1), "role"),
  provider = vapply(components, `[[`, character(1), "provider"),
  source_url = vapply(components, function(x) as.character(x$url), character(1)),
  files = vapply(components, function(component) {
    sum(startsWith(manifest$path, component$target))
  }, integer(1)),
  bytes = vapply(components, function(component) {
    sum(manifest$bytes[startsWith(manifest$path, component$target)])
  }, numeric(1)),
  stringsAsFactors = FALSE
)
rp_write_csv_atomic(
  external, file.path(staging, "provenance", "external_source_manifest.csv")
)
if (!is.null(downloads)) {
  rp_write_csv_atomic(
    downloads, file.path(staging, "provenance", "raster_download_manifest.csv")
  )
}

rp_write_lines_atomic(
  c(
    paste0("# Canonical analysis-input snapshot: ", snapshot_id),
    "",
    paste0("Built from commit ", rp_git_commit(), " on ",
           format(Sys.time(), tz = "UTC", usetz = TRUE), "."),
    "",
    "This archive is the immutable starting point of the canonical analysis",
    "workflow. It carries every input the locked publication pipeline consumes",
    "and cannot regenerate on a clean runner:",
    "",
    "- `analysis_inputs/results/ecological_v11_pigmentation_hurdle/`: the frozen",
    "  two-part phenotype stage outputs.",
    "- `analysis_inputs/results/ecological_v15_multiscale_hotspots/`: the frozen",
    "  1-km multiscale cell context.",
    "- `analysis_inputs/results/public_rasters/mlit_human_forest_edge_2021/`: the",
    "  MLIT-derived human-landscape 1-km layers.",
    "- `analysis_inputs/results/enmeval_aicc_reselected/predictions/`: the five",
    "  committed Bombus prediction surfaces. These are restored, not",
    "  regenerated; see reproducibility/reproduction_summary.md.",
    "- `analysis_inputs/rasters/population_count_Japan_crop.tif`: the WorldPop",
    "  population layer.",
    "- `analysis_inputs/mlit_l03_2021/`: the raw MLIT primary-mesh archives the",
    "  local-human-context stage re-processes.",
    "- `analysis_inputs/mlit_did_2015/`: the MLIT A16-15 Densely Inhabited",
    "  District archive the DID sensitivity stage uses.",
    "",
    "`SNAPSHOT_MANIFEST.csv` records the SHA-256, byte size, component, provider",
    "and source URL of every member. `provenance/` carries the raster download",
    "and preparation manifests from the reconstruction that produced these",
    "layers.",
    "",
    "Nothing in this archive is a result, and nothing in it may be edited by",
    "hand. To change its contents, rerun the raw-data reconstruction workflow",
    "with a new snapshot identifier and commit the new descriptor."
  ),
  file.path(staging, "SNAPSHOT_README.md")
)

descriptor <- list(
  snapshot_id = snapshot_id,
  release_tag = release_tag,
  asset_name = asset_name,
  asset_sha256 = "",
  built_from_commit = rp_git_commit(),
  built_at_utc = format(Sys.time(), tz = "UTC", usetz = TRUE),
  components = external,
  contents = manifest
)
dir.create(dirname(descriptor_path), recursive = TRUE, showWarnings = FALSE)
rp_write_atomic(descriptor_path, function(temporary) {
  writeLines(
    jsonlite::toJSON(descriptor, auto_unbox = TRUE, pretty = TRUE, na = "null"),
    temporary, useBytes = TRUE
  )
})

cat("Staged canonical snapshot at ", normalizePath(staging), "\n", sep = "")
print(external, row.names = FALSE)
cat("members: ", nrow(manifest), "; bytes: ", sum(manifest$bytes), "\n", sep = "")
