#!/usr/bin/env Rscript

# Compare alternative continuous summaries of potential Bombus availability.
# The input is the prepared inclusive-primary photograph table generated by
# scripts/run_reanalysis.R. All models use one common complete-case cohort and
# one shared spatial fold assignment.

args <- commandArgs(trailingOnly = TRUE)
repo_root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1L])), ".."), winslash = "/", mustWork = TRUE)
source(file.path(repo_root, "R", "analysis_core.R"))
source(file.path(repo_root, "R", "sdm.R"))
source(file.path(repo_root, "R", "reanalysis.R"))
source(file.path(repo_root, "R", "bombus_availability.R"))

usage <- function() {
  paste(
    "Usage:",
    "  Rscript scripts/run_bombus_availability_sensitivity.R [options]",
    "",
    "Options:",
    "  --input PATH       Prepared inclusive-primary CSV",
    "                     (default: results/reanalysis/v2_2_2/inputs/inclusive__primary.csv)",
    "  --config PATH      Reanalysis config (default: config/reanalysis.yml)",
    "  --output-dir PATH  New output directory",
    "                     (default: results/reanalysis/v2_2_2/bombus_availability)",
    "  --help             Show this help",
    sep = "\n"
  )
}

values <- list(
  input = file.path(repo_root, "results", "reanalysis", "v2_2_2", "inputs", "inclusive__primary.csv"),
  config = file.path(repo_root, "config", "reanalysis.yml"),
  output_dir = file.path(repo_root, "results", "reanalysis", "v2_2_2", "bombus_availability"),
  help = FALSE
)
map <- c("--input" = "input", "--config" = "config", "--output-dir" = "output_dir")
i <- 1L
while (i <= length(args)) {
  if (args[[i]] %in% c("--help", "-h")) {
    values$help <- TRUE
    i <- i + 1L
  } else if (args[[i]] %in% names(map)) {
    if (i == length(args)) stop("Missing value after ", args[[i]], call. = FALSE)
    values[[map[[args[[i]]]]]] <- args[[i + 1L]]
    i <- i + 2L
  } else {
    stop("Unknown argument: ", args[[i]], call. = FALSE)
  }
}
if (values$help) {
  cat(usage(), "\n")
  quit(save = "no", status = 0L)
}
if (!file.exists(values$input)) stop("Prepared analysis input not found: ", values$input, call. = FALSE)
if (!file.exists(values$config)) stop("Config not found: ", values$config, call. = FALSE)
if (file.exists(values$output_dir) && length(list.files(values$output_dir, all.files = TRUE, no.. = TRUE))) {
  stop("Refusing to overwrite non-empty output directory: ", values$output_dir, call. = FALSE)
}
dir.create(values$output_dir, recursive = TRUE, showWarnings = FALSE)

config <- read_reanalysis_config(values$config)
data <- utils::read.csv(values$input, stringsAsFactors = FALSE, check.names = FALSE)
data <- add_reanalysis_transforms(data, config)
data <- add_bombus_availability_indices(data)

outcome <- as.character(config$primary_outcome)
environment <- as.character(unlist(config$environment_predictors))
availability <- bombus_availability_predictors()
required <- unique(c("analysis_id", "longitude", "latitude", outcome, environment, availability))
missing <- setdiff(required, names(data))
if (length(missing)) stop("Sensitivity input is missing: ", paste(missing, collapse = ", "), call. = FALSE)

# One common cohort prevents apparent differences caused by changing missingness.
common <- finite_complete_rows(data, c(outcome, environment, availability))
analysis <- data[common, , drop = FALSE]
if (!nrow(analysis)) stop("No complete rows for Bombus availability sensitivity.", call. = FALSE)
folds <- make_spatial_block_folds(analysis, folds = config$spatial_block_cv$folds)
analysis$spatial_fold <- folds$spatial_fold[match(analysis$analysis_id, folds$analysis_id)]

variants <- c(environment_only = NA_character_, setNames(availability, availability))
coefficient_rows <- list()
performance_rows <- list()
fold_rows <- list()
for (variant in names(variants)) {
  bombus_term <- variants[[variant]]
  predictors <- if (is.na(bombus_term)) environment else c(environment, bombus_term)
  fit <- fit_standardized_association(analysis, outcome, predictors)
  cv <- blocked_cv_association(
    analysis,
    outcome,
    predictors,
    configured_folds = seq_len(as.integer(config$spatial_block_cv$folds))
  )
  meta <- list(
    model_variant = variant,
    bombus_index = if (is.na(bombus_term)) "none" else bombus_term,
    records_common = nrow(analysis)
  )
  coefficient_rows[[variant]] <- prefix_columns(fit$coefficients, meta)
  cv_performance <- cv$performance
  names(cv_performance)[names(cv_performance) == "records_complete"] <- "records_complete_cv"
  performance_rows[[variant]] <- prefix_columns(cbind(fit$performance, cv_performance), meta)
  fold_rows[[variant]] <- prefix_columns(cv$fold_performance, meta)
}

coefficients <- do.call(rbind, coefficient_rows)
performance <- do.call(rbind, performance_rows)
performance_by_fold <- do.call(rbind, fold_rows)
rownames(coefficients) <- rownames(performance) <- rownames(performance_by_fold) <- NULL

baseline <- performance$q_squared_cv[performance$model_variant == "environment_only"]
performance$delta_q_squared_vs_environment <- performance$q_squared_cv - baseline
performance <- performance[order(-performance$q_squared_cv), , drop = FALSE]

utils::write.csv(coefficients, file.path(values$output_dir, "coefficients.csv"), row.names = FALSE, na = "")
utils::write.csv(performance, file.path(values$output_dir, "performance.csv"), row.names = FALSE, na = "")
utils::write.csv(performance_by_fold, file.path(values$output_dir, "performance_by_fold.csv"), row.names = FALSE, na = "")
utils::write.csv(
  data.frame(
    group = c("widespread", "montane"),
    species = c("ardens;diversus", "beaticola;consobrinus;honshuensis"),
    stringsAsFactors = FALSE
  ),
  file.path(values$output_dir, "species_groups.csv"),
  row.names = FALSE
)

print(performance[c("model_variant", "records_common", "q_squared_cv", "delta_q_squared_vs_environment", "rmse", "mae")], row.names = FALSE)
