# Post hoc bidirectional local colour-state asymmetry diagnostic.
#
# The diagnostic reuses the locked primary local-isolate graph and asks whether
# a pigmented cell surrounded by white neighbours is more common than a white
# cell surrounded by pigmented neighbours, beyond the asymmetry the fitted
# natural environment-plus-SPDE baseline and the observed sampling design
# already produce. It is a symmetry diagnostic, not a pre-specified test.

args <- commandArgs(trailingOnly = TRUE)
source("R/pipeline_support.R")
source("R/reproducibility.R")
source("R/candidate_null_tools.R")
source("R/local_pigmented_isolates.R")
source("R/local_state_asymmetry.R")

# Declared like every other stage script. sf is used for the analysis-CRS
# deviation check below; without this the stage would fail there, deep in a
# geometry call, rather than here with the package named.
hb_require_packages(c("sf"))

arg_value <- function(name, default = NULL) hb_arg_value(args, name, default)

cells_path <- arg_value(
  "--cells",
  "results/ecological_v15_multiscale_hotspots/multiscale_hotspot_cells_1km.csv"
)
checkpoint_path <- arg_value(
  "--presence-checkpoint",
  paste0(
    "results/ecological_v16_predictive_replication/checkpoints/",
    "national_environment_spde_presence_draws1000.rds"
  )
)
output_dir <- arg_value(
  "--output", "results/ecological_v23_local_state_asymmetry"
)
required_maps <- as.integer(arg_value("--required-maps", "1000"))
pseudocount <- as.numeric(arg_value("--pseudocount", "0.5"))
analysis_seed <- as.integer(arg_value("--seed", "20260725"))

if (!is.finite(required_maps) || required_maps < 1L) {
  stop("--required-maps must be a positive integer.", call. = FALSE)
}
if (!is.finite(pseudocount) || pseudocount <= 0) {
  stop("--pseudocount must be finite and positive.", call. = FALSE)
}
if (!file.exists(cells_path)) {
  stop(
    "Missing 1-km cell table: ", cells_path, ". It is generated by the ",
    "multiscale hotspot stage from the canonical analysis-input snapshot; ",
    "see reproducibility/pipeline_dag.md.", call. = FALSE
  )
}
if (!file.exists(checkpoint_path)) {
  stop(
    "Missing natural presence predictive checkpoint: ", checkpoint_path,
    ". It is generated by the natural predictive model stage; ",
    "see reproducibility/pipeline_dag.md.", call. = FALSE
  )
}

input_hashes <- c(cells = rp_sha256(cells_path), checkpoint = rp_sha256(checkpoint_path))
message("[v23] cells sha256:      ", input_hashes[["cells"]])
message("[v23] checkpoint sha256: ", input_hashes[["checkpoint"]])

# ---------------------------------------------------------------------------
# The 1-km cell table.
# ---------------------------------------------------------------------------
cells <- utils::read.csv(
  cells_path, check.names = FALSE, stringsAsFactors = FALSE
)
environment_columns <- c(
  "broad50km_pc1", "broad50km_pc2", "within50km_pc1", "within50km_pc2"
)
v23_require_columns(
  cells,
  c(
    "exact_site_id", "n_pigmented", "n_observations",
    "n_independent_sites", "longitude", "latitude", "x_km", "y_km",
    "observed_x_km", "observed_y_km", "spatial_fold", "spatial_unit_km",
    "grid_offset_km", environment_columns
  ),
  "cells"
)
if (anyDuplicated(cells$exact_site_id)) {
  stop("Cell identifiers are not unique in ", cells_path, call. = FALSE)
}
if (!all(cells$spatial_unit_km == 1)) {
  stop(
    "The asymmetry diagnostic requires the 1-km cell table; the supplied ",
    "table declares spatial_unit_km = ",
    paste(unique(cells$spatial_unit_km), collapse = ", "), ".", call. = FALSE
  )
}
if (any(!is.finite(as.matrix(cells[environment_columns])))) {
  stop(
    "Locked environmental columns contain non-finite values: ",
    paste(environment_columns, collapse = ", "), call. = FALSE
  )
}
if (any(!is.finite(cells$n_observations)) || any(cells$n_observations < 1)) {
  stop("Every cell must have at least one observation.", call. = FALSE)
}
if (any(!is.finite(cells$n_pigmented)) || any(cells$n_pigmented < 0) ||
    any(cells$n_pigmented > cells$n_observations)) {
  stop("Observed pigmented counts fall outside [0, n_observations].",
       call. = FALSE)
}

# The graph is built in the locked analysis projection. `x_km`/`y_km` are the
# snapped 1-km cell centres and `observed_x_km`/`observed_y_km` are the
# aggregated observation coordinates they were snapped from. Two checks pin the
# geometry down: the snapping must be exactly the locked 1-km rule, and the
# aggregated projected coordinates must agree with the locked analysis CRS
# recomputed from longitude and latitude. A table produced under a different
# projection deviates by hundreds of kilometres, not by rounding.
hb_require_packages("sf")
analysis_crs <- paste(
  "+proj=laea +lat_0=36 +lon_0=137 +x_0=0 +y_0=0",
  "+datum=WGS84 +units=m +no_defs"
)
offset <- as.numeric(cells$grid_offset_km)
expected_x <- (floor((cells$observed_x_km - offset) / cells$spatial_unit_km) + 0.5) *
  cells$spatial_unit_km + offset
expected_y <- (floor((cells$observed_y_km - offset) / cells$spatial_unit_km) + 0.5) *
  cells$spatial_unit_km + offset
snapping_deviation_km <- max(
  abs(expected_x - cells$x_km), abs(expected_y - cells$y_km)
)
if (!is.finite(snapping_deviation_km) || snapping_deviation_km > 1e-9) {
  stop(
    "Cell centres are not the locked 1-km snapping of the observed ",
    "coordinates (maximum deviation ", signif(snapping_deviation_km, 6),
    " km).", call. = FALSE
  )
}
projected <- sf::st_coordinates(sf::st_transform(
  sf::st_as_sf(
    cells[c("longitude", "latitude")], coords = c("longitude", "latitude"),
    crs = 4326
  ),
  analysis_crs
)) / 1000
crs_deviation_km <- max(
  abs(projected[, 1] - cells$observed_x_km),
  abs(projected[, 2] - cells$observed_y_km)
)
if (!is.finite(crs_deviation_km) || crs_deviation_km > 2) {
  stop(
    "Stored projected coordinates do not match the locked analysis CRS ",
    "(maximum deviation ", signif(crs_deviation_km, 6), " km). ",
    "The cell table was produced under a different projection.", call. = FALSE
  )
}

# ---------------------------------------------------------------------------
# The cross-fitted natural predictive maps.
# ---------------------------------------------------------------------------
checkpoint <- readRDS(checkpoint_path)
if (!is.null(checkpoint$model) &&
    !identical(checkpoint$model, "national_environment_spde_presence")) {
  stop(
    "The predictive checkpoint holds model '", checkpoint$model,
    "' rather than the natural presence baseline.", call. = FALSE
  )
}
checkpoint_order_matches <- identical(
  as.character(checkpoint$cell_id), as.character(cells$exact_site_id)
)
presence <- v18_align_result(checkpoint, cells, "presence")
simulated_counts <- presence$draws

available_maps <- ncol(simulated_counts)
if (available_maps < required_maps) {
  stop(
    "Only ", available_maps, " cross-fitted natural predictive maps are ",
    "available; the diagnostic requires exactly ", required_maps, ".",
    call. = FALSE
  )
}
simulated_counts <- simulated_counts[, seq_len(required_maps), drop = FALSE]

if (!hb_close_enough(presence$trials, as.numeric(cells$n_observations))) {
  stop(
    "Trial counts in the predictive checkpoint do not match the cell table. ",
    "The checkpoint and the cell table are not the same analysis.",
    call. = FALSE
  )
}
if (!hb_close_enough(presence$observed, as.numeric(cells$n_pigmented))) {
  stop(
    "Observed pigmented counts in the predictive checkpoint do not match the ",
    "cell table.", call. = FALSE
  )
}
trial_matrix <- matrix(
  as.numeric(cells$n_observations), nrow(simulated_counts), ncol(simulated_counts)
)
if (any(!is.finite(simulated_counts)) || any(simulated_counts < 0) ||
    any(simulated_counts > trial_matrix)) {
  stop(
    "At least one predictive count lies outside [0, n_observations]. ",
    "The predictive maps are not binomial replicates of the observed design.",
    call. = FALSE
  )
}
if (any(abs(simulated_counts - round(simulated_counts)) > 1e-9)) {
  stop("Predictive counts are not integers.", call. = FALSE)
}

observed_counts <- matrix(as.numeric(cells$n_pigmented), ncol = 1L)
trials <- as.numeric(cells$n_observations)

# ---------------------------------------------------------------------------
# The locked primary local-isolate configuration, read programmatically.
# ---------------------------------------------------------------------------
configurations <- v20_configuration_table()
primary_configuration <- configurations[
  configurations$role == "primary", , drop = FALSE
]
if (nrow(primary_configuration) != 1L) {
  stop(
    "The locked primary local-isolate configuration could not be found: ",
    nrow(primary_configuration), " rows with role 'primary'.", call. = FALSE
  )
}
message(
  "[v23] locked primary configuration: ", primary_configuration$configuration,
  " (radius ", primary_configuration$radius_km, " km, caliper ",
  primary_configuration$environment_caliper, ", minimum neighbours ",
  primary_configuration$minimum_neighbours, ", same-fold-only ",
  primary_configuration$same_fold_only, ")"
)

graph <- v20_neighbour_graph(
  cells,
  radius_km = primary_configuration$radius_km,
  environment_caliper = primary_configuration$environment_caliper,
  minimum_neighbours = primary_configuration$minimum_neighbours,
  same_fold_only = primary_configuration$same_fold_only
)
graph_supported <- v23_graph_support(graph, nrow(cells))
if (!any(graph_supported)) {
  stop("The locked graph supports no focal cells.", call. = FALSE)
}

# ---------------------------------------------------------------------------
# Both directions, on the identical graph, under all three state definitions.
# ---------------------------------------------------------------------------
rules <- v23_state_rule_table()
summary_rows <- list()
null_rows <- list()
candidate_rows <- list()
for (index in seq_len(nrow(rules))) {
  rule <- rules[index, , drop = FALSE]
  message("[v23] evaluating state rule: ", rule$state_rule)
  observed <- v23_directional_profiles(
    observed_counts, trials, graph,
    white_max_share = rule$white_max_share,
    pigmented_min_share = rule$pigmented_min_share,
    pseudocount = pseudocount
  )
  simulated <- v23_directional_profiles(
    simulated_counts, trials, graph,
    white_max_share = rule$white_max_share,
    pigmented_min_share = rule$pigmented_min_share,
    pseudocount = pseudocount
  )
  summary_rows[[length(summary_rows) + 1L]] <-
    v23_asymmetry_summary(observed, simulated, rule$state_rule)
  null_block <- simulated$summary
  null_block$analysis_spec_version <- v23_analysis_spec_version
  null_block$analysis_status <- "post_hoc_diagnostic"
  null_block$state_rule <- rule$state_rule
  null_block$pseudocount <- pseudocount
  null_rows[[length(null_rows) + 1L]] <- null_block
  candidate_rows[[length(candidate_rows) + 1L]] <-
    v23_observed_candidates(observed, cells$exact_site_id, rule$state_rule)
}

summary <- do.call(rbind, summary_rows)
null <- do.call(rbind, null_rows)
candidates <- do.call(rbind, candidate_rows)
rownames(summary) <- NULL
rownames(null) <- NULL
rownames(candidates) <- NULL

if (!all(table(null$state_rule) == required_maps)) {
  stop(
    "The null distribution does not contain exactly ", required_maps,
    " maps for every state rule.", call. = FALSE
  )
}

primary_metric <- summary[
  summary$state_rule == "legacy_any_pigmented" &
    summary$metric == "log_rate_ratio", , drop = FALSE
]
if (nrow(primary_metric) != 1L) {
  stop("Primary asymmetry metric was not generated exactly once.", call. = FALSE)
}

metadata <- data.frame(
  field = c(
    "analysis_spec_version", "generated_at_utc", "analysis_status",
    "commit", "primary_state_rule", "primary_asymmetry_metric",
    "positive_direction", "neighbourhood_definition",
    "locked_configuration_id", "locked_radius_km",
    "locked_environment_caliper", "locked_minimum_neighbours",
    "locked_same_fold_only", "natural_reference", "n_natural_maps",
    "analysis_crs_max_deviation_km", "cell_snapping_max_deviation_km",
    "n_natural_maps_available", "pseudocount", "analysis_crs",
    "predictive_seed_source", "analysis_seed",
    "cells_sha256", "presence_checkpoint_sha256",
    "checkpoint_row_order_matched_cells", "n_cells", "n_graph_supported_cells",
    "claim_ceiling"
  ),
  value = c(
    v23_analysis_spec_version,
    format(Sys.time(), tz = "UTC", usetz = TRUE),
    "post_hoc symmetry diagnostic; not pre-specified",
    rp_git_commit(),
    "legacy_any_pigmented",
    "log ratio of opportunity-normalized pigmented-in-white rate to white-in-pigmented rate",
    "positive values indicate relatively more pigmented-in-white events",
    paste(
      "locked primary local-isolate graph:",
      paste0(primary_configuration$radius_km, " km radius;"),
      paste0("environment caliper ", primary_configuration$environment_caliper, ";"),
      paste0("minimum neighbours ", primary_configuration$minimum_neighbours, ";"),
      paste0("same-fold-only ", primary_configuration$same_fold_only)
    ),
    primary_configuration$configuration,
    primary_configuration$radius_km,
    primary_configuration$environment_caliper,
    primary_configuration$minimum_neighbours,
    primary_configuration$same_fold_only,
    paste(
      required_maps,
      "cross-fitted natural predictive maps with observed trial counts fixed"
    ),
    required_maps,
    signif(crs_deviation_km, 6),
    signif(snapping_deviation_km, 6),
    available_maps,
    pseudocount,
    analysis_crs,
    paste(
      "INLA::inla.posterior.sample seed and the binomial replicate seed are",
      "set per fold in the natural predictive model stage"
    ),
    analysis_seed,
    input_hashes[["cells"]],
    input_hashes[["checkpoint"]],
    checkpoint_order_matches,
    nrow(cells),
    sum(graph_supported),
    paste(
      "directional local colour-state asymmetry relative to the fitted natural baseline;",
      "not a mechanism, transition rate, mutation rate, introduction rate, or evolutionary direction"
    )
  ),
  stringsAsFactors = FALSE
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
rp_write_csv_atomic(rules, file.path(output_dir, "local_state_asymmetry_rules.csv"))
rp_write_csv_atomic(summary, file.path(output_dir, "local_state_asymmetry_summary.csv"))
rp_write_csv_atomic(null, file.path(output_dir, "local_state_asymmetry_null.csv"))
rp_write_csv_atomic(
  candidates, file.path(output_dir, "local_state_asymmetry_candidates.csv")
)
rp_write_csv_atomic(
  metadata, file.path(output_dir, "local_state_asymmetry_metadata.csv")
)

readme <- c(
  "# v23 post hoc local colour-state asymmetry diagnostic",
  "",
  paste(
    "This stage applies the same response-blind 10-km environmental-neighbourhood",
    "graph to both directions of local colour-state discordance: a pigmented focal",
    "cell among white neighbours and a white focal cell among pigmented neighbours."
  ),
  "",
  paste(
    "The primary rule mirrors the locked pigmented-isolate definition. Pure-cell",
    "and 10/90 share rules are retained as classification sensitivities. Counts are",
    "normalized by the number of graph-supported focal cells in the corresponding",
    "state before the directional rates are compared."
  ),
  "",
  paste0(
    "The observed log rate ratio is compared with the same statistic from each of ",
    required_maps, " cross-fitted natural predictive maps. This is a post hoc ",
    "symmetry diagnostic. It does not estimate a biological transition, mutation, ",
    "dispersal, planting, or evolutionary rate, and it must not be described as ",
    "pre-specified."
  ),
  "",
  "## Files",
  "",
  "- `local_state_asymmetry_rules.csv`: the three predeclared state definitions.",
  "- `local_state_asymmetry_summary.csv`: observed value, null mean and SD, 2.5%",
  "  and 97.5% null quantiles, upper-, lower-, and two-sided Monte Carlo p, the",
  "  observed percentile, and the number of usable natural maps, for every metric",
  "  and every state rule.",
  "- `local_state_asymmetry_null.csv`: the per-map null statistics the summary is",
  "  computed from, so every p-value can be recomputed independently.",
  "- `local_state_asymmetry_candidates.csv`: the observed directional events.",
  "- `local_state_asymmetry_metadata.csv`: locked configuration, seeds, input",
  "  checksums, and the claim ceiling.",
  "- `local_state_asymmetry_validation.csv` and `VALIDATION.md`: independent",
  "  validation of the outputs in this directory."
)
rp_write_lines_atomic(readme, file.path(output_dir, "README.md"))

cat("v23 local state-asymmetry outputs written to ",
    normalizePath(output_dir), "\n", sep = "")
print(primary_metric, row.names = FALSE)
