#!/usr/bin/env Rscript

# Reanalysis-only loader shim. The scientific stage is still the repository's
# scripts/run_bombus_limitation_gate.R; only its module-loading line is replaced
# so the current R/local_bombus_turnover.R is sourced explicitly. This prevents
# an archived compatibility helper from leaking into the fresh 1,965-source run.
script_path <- "scripts/run_bombus_limitation_gate.R"
code <- readLines(script_path, warn = FALSE, encoding = "UTF-8")
needle <- 'hb_load_modules("bombus_limitation_gate")'
hit <- which(trimws(code) == needle)
if (length(hit) != 1L) {
  stop("Expected exactly one Bombus limitation module-loading line.", call. = FALSE)
}
code[hit] <- 'sys.source("R/local_bombus_turnover.R", envir = .GlobalEnv)'

# Evaluate the otherwise unchanged stage with this wrapper's command-line
# arguments. The current helper uses the same four 50-km response-blind PCA axes
# generated by the historical upstream sequence.
eval(parse(text = code, keep.source = FALSE), envir = .GlobalEnv)
