#!/usr/bin/env python3
from pathlib import Path

path = Path("submission/jbi/JBI_main_manuscript_anonymized.md")
text = path.read_text(encoding="utf-8")
start = text.index("## Introduction")
end = text.index("## Materials and Methods")

intro = r'''## Introduction

Geographical trait variation is easy to map and easy to overinterpret. The same regional cline can reflect physiological responses to environment, demographic or dispersal history, and natural selection, while the organisms and interactions invoked to explain that cline are themselves geographically structured. For traits that must be measured directly, this inferential problem is compounded by a measurement problem: range-wide data are often coarse, whereas quantitative measurements are available from relatively few populations. Trait biogeography therefore faces a sequence of dependent questions. First, can the phenotype be measured densely enough to reveal its true geographical structure? Second, once that structure is visible, which associations are broad geographical correspondences and which are plausible local ecological processes? Third, after a broad natural template has been established, what should count as a genuinely unusual local departure from it?

Flower colour makes these problems especially clear. Floral pigmentation can covary with abiotic conditions while also mediating interactions with animal pollinators (Rausher, 2008; Koski & Ashman, 2015; Trunschke et al., 2021). Yet many range-wide studies necessarily compare discrete colour morphs, whereas quantitative reflectance or pigment measurements are usually available for fewer populations (Arista et al., 2013; Koski & Galloway, 2020). This distinction matters biologically as well as statistically. A threshold-like loss or activation of anthocyanin-pathway expression can separate white and visibly pigmented flowers, whereas variation among already pigmented flowers can additionally reflect pigment amount and floral optics (Dick et al., 2011; van der Kooi et al., 2016; Tasaki et al., 2022). A single white-to-pink axis can therefore merge two potentially different ecological transitions: whether a visible pigment state is expressed and how intense that state becomes once expressed.

Digital imagery offers a way to bridge the gap between broad categorical maps and small-sample quantitative measurements. Biodiversity platforms increasingly provide photographs from which visible phenotypes can be recovered (Laitly et al., 2021; Luong et al., 2023; McKenzie et al., 2026), while iEcology extends this idea to digital material originally created for other purposes (Jarić et al., 2020). We used YAMAP, a hiking-navigation and activity-diary platform, because public hiking activities can retain route-linked photograph locations across mountain systems. In a matched 2023–2025 Supplementary benchmark, the author-screened YAMAP retrieval yielded 1,964 georeferenced focal-species records compared with 516 iNaturalist observations with photographs; the matched GBIF image set was almost entirely syndicated from iNaturalist (Appendix S1). This does not make YAMAP unbiased. Its observation process is different: users document hikes rather than submit focal-species records, potentially reducing selection conditioned specifically on taxon reporting while retaining route choice, access, flower conspicuousness and subject-selection biases. For a mountain herb, this sampling frame is also deliberately concentrated in natural and semi-natural mountain environments relevant to wild-population geography, although it cannot establish wild provenance for every photograph. Exhaustive author screening and deterministic image phenotyping then convert that recreational image stream into a quantitative trait dataset rather than a direct occurrence export.

Solving the measurement problem, however, exposes a second difficulty rather than removing it. Once a detailed national flower-colour map exists, climate, topography, residual spatial history and predicted pollinator distributions can all share the same broad geography. Species-distribution models (SDMs) are themselves generated from environmental predictors, so a national flower-colour–pollinator association can be statistically precise while remaining biologically ambiguous (Soberón, 2007; Paciorek, 2010; Hanks et al., 2015). This is especially problematic if the proposed biotic process should act among neighbouring populations while both plant and pollinator vary across entire regions. We therefore treat spatial scale as part of the ecological hypothesis rather than as a technical afterthought. Broad environmental and spatial structure is estimated first; only then is the pollinator question asked at abrupt nearby colour boundaries, where the comparison unit is local rather than another pair of national maps (Araújo & Rozenfeld, 2014). This change of scale cannot eliminate unmeasured environmental confounding, but it changes the biological quantity being tested.

*Campanula punctata* provides unusually strong natural-history grounds for such a local test. Its large tubular flowers are effectively pollinated by bumblebees, and realized Bombus assemblages vary geographically. In this species, flower–pollinator size matching can affect pollen removal and floral trait selection (Nagano et al., 2014), while in the Izu Islands the loss of bumblebee-dominated pollination is associated with major changes in reproductive ecology and breeding system (Inoue & Amano, 1986; Inoue, 1988). These studies do not show that bumblebees determine white versus pigmented flowers, but they make a directional colour hypothesis biologically meaningful. If visible pigmentation contributes to attraction or detection by important bumblebee visitors, the reproductive benefit of maintaining a pigmented state should be greater where those pollinators are locally available and may relax where their availability declines. This prediction concerns the maintenance of a visible pigment state more directly than progressive darkening among flowers that are already pigmented. We therefore focus the directional test on the broadly distributed, directly documented focal pollinators *B. ardens* and *B. diversus*. Montane and alpine Bombus species are not pooled into the primary availability metric because their niches overlap the same high-elevation geography in which pigmented flowers are common; they instead provide a guardrail against mistaking shared mountain biogeography for a pollinator mechanism.

Establishing a broad natural template also creates a third inferential problem: how should locally surprising populations be interpreted? A large fitted residual is not automatically a biological anomaly, because residual magnitude also reflects model uncertainty, leverage and sampling geometry. This distinction matters in *C. punctata* because the species is cultivated ornamentally, making planting, escape or introgression plausible provenance hypotheses for some unusual populations. We therefore do not begin with human variables and search for matching residuals. Instead, we first define a biologically readable local configuration—a pigmented cell embedded among geographically close, environmentally similar white neighbours—and ask how often the fitted natural geography itself generates the same configuration. Only after those locations are fixed do we examine human context. The mountain-focused YAMAP sampling frame consequently returns as both an advantage and a limitation: it enriches the natural mountain habitats relevant to the broad and local ecological questions, but it may compress the urban–rural gradient available to the final human-context test.

These three questions are therefore linked rather than parallel. Quantitative image phenotyping makes the national environmental–spatial template possible; that template reveals why same-scale Bombus overlap is difficult to interpret and motivates a local boundary test; and the same template supplies the predictive reference needed to calibrate local departures before human context is considered. We ask: (1) what broad environmental and spatial structure organizes pigmentation state and conditional visible intensity across Japan; (2) within that template, whether the sharpest nearby white–pigmented transitions align directionally with availability of focal bumblebee pollinators; and (3) whether locally discordant pigmented populations are more frequent than expected under the broad natural model and, once defined independently, occupy distinctive human context. The goal is not to partition all causal variance among environment, pollinators and people, but to let each ecological question determine the spatial scale and comparison unit at which its interpretation is most defensible.

'''

new_text = text[:start] + intro + text[end:]
path.write_text(new_text, encoding="utf-8")
print("Rewrote JBI Introduction around dependent biogeographical bottlenecks.")
