#!/usr/bin/env python3
from pathlib import Path

path = Path('submission/jbi/JBI_main_manuscript_anonymized.md')
text = path.read_text(encoding='utf-8')
start = text.index('## Introduction')
end = text.index('## Materials and Methods')

intro = r'''## Introduction

Geographical variation within species is not merely descriptive noise around a species mean. Intraspecific trait variation can alter individual performance, population persistence, species interactions and the ecological breadth of populations across heterogeneous environments (Westerband et al., 2021). Understanding how such variation is organized across a species range is therefore central to explaining local adaptation and the geographical mosaic of ecological interactions. Yet the same phenotype can be shaped by several processes at once: abiotic conditions, dispersal and population history, biotic interactions and, increasingly, human movement or habitat modification. These alternatives matter because they imply different mechanisms and different expectations for how trait distributions should respond when environments or interacting species change.

Flower colour is an unusually integrative trait for addressing this problem. Floral pigmentation is simultaneously a physiological phenotype and a reproductive signal: pigments and floral optics can covary with abiotic conditions, while visible colour can influence pollinator attraction, mating patterns and reproductive success (Rausher, 2008; Koski & Ashman, 2015; Trunschke et al., 2021). Geographic colour polymorphisms therefore provide a tractable window into how multiple selective agents and spatial history combine within one conspicuous phenotype. But that integrative potential creates an inferential danger. A climate gradient, a pollinator turnover and a historical population boundary can generate similar spatial patterns, so studying each process separately—or forcing them into one same-scale regression—can mistake shared geography for mechanism. The ecological need is therefore not simply for more predictors, but for an integrated design in which each process is examined at the spatial scale and comparison unit at which its biological meaning is most defensible.

That integration first requires a phenotype measured densely enough to reveal the geography that subsequent mechanisms must explain. Range-wide flower-colour studies often rely on discrete morph frequencies, whereas quantitative reflectance or pigment measurements are usually available from fewer populations (Arista et al., 2013; Koski & Galloway, 2020). This matters because a single white-to-pink axis can merge biologically distinct transitions. A threshold-like loss or activation of anthocyanin-pathway expression can separate white and visibly pigmented flowers, whereas variation among already pigmented flowers can additionally reflect pigment amount and floral optics (Dick et al., 2011; van der Kooi et al., 2016; Tasaki et al., 2022). Distinguishing whether pigmentation is expressed from how intense that pigmentation becomes is therefore necessary not only for measurement precision, but also for asking whether different ecological processes act on different components of the phenotype.

Digital imagery offers a way to bridge the gap between broad categorical maps and small-sample quantitative measurements. Biodiversity platforms increasingly provide photographs from which visible phenotypes can be recovered (Laitly et al., 2021; Luong et al., 2023; McKenzie et al., 2026), while iEcology extends this idea to digital material originally created for other purposes (Jarić et al., 2020). We used YAMAP, a hiking-navigation and activity-diary platform, because public hiking activities can retain route-linked photograph locations across mountain systems. In a matched 2023–2025 Supplementary benchmark, the author-screened YAMAP retrieval yielded 1,964 georeferenced focal-species records compared with 516 iNaturalist observations with photographs; the matched GBIF image set was almost entirely syndicated from iNaturalist (Appendix S1). This does not make YAMAP unbiased. Its observation process is different: users document hikes rather than submit focal-species records, potentially reducing selection conditioned specifically on taxon reporting while retaining route choice, access, flower conspicuousness and subject-selection biases. For a mountain herb, this sampling frame is also deliberately concentrated in natural and semi-natural mountain environments relevant to wild-population geography, although it cannot establish wild provenance for every photograph. Exhaustive author screening and deterministic image phenotyping then convert that recreational image stream into a quantitative trait dataset rather than a direct occurrence export.

Once this measurement problem is solved, integration becomes more—not less—important. A detailed national flower-colour map exposes the fact that climate, topography, residual spatial history and predicted pollinator distributions can all share the same broad geography. Species-distribution models (SDMs) are themselves generated from environmental predictors, so a national flower-colour–pollinator association can be statistically precise while remaining biologically ambiguous (Soberón, 2007; Paciorek, 2010; Hanks et al., 2015). At the same time, genuine biotic selection is expected to arise through encounters among local plant and pollinator populations rather than through abstract overlap of two national surfaces (Araújo & Rozenfeld, 2014). An integrated analysis must therefore connect scales rather than collapse them: broad environment and continuous space should first establish the geographical template, after which a local biotic hypothesis can be asked at abrupt nearby boundaries. In this sense, integration means linking complementary pieces of evidence while preserving the ecological scale of each process.

*Campanula punctata* provides unusually strong natural-history grounds for such a local test. Its large tubular flowers are effectively pollinated by bumblebees, and realized Bombus assemblages vary geographically. In this species, flower–pollinator size matching can affect pollen removal and floral trait selection (Nagano et al., 2014), while in the Izu Islands the loss of bumblebee-dominated pollination is associated with major changes in reproductive ecology and breeding system (Inoue & Amano, 1986; Inoue, 1988). These studies do not show that bumblebees determine white versus pigmented flowers, but they make a directional colour hypothesis biologically meaningful. If visible pigmentation contributes to attraction or detection by important bumblebee visitors, the reproductive benefit of maintaining a pigmented state should be greater where those pollinators are locally available and may relax where their availability declines. This prediction concerns the maintenance of a visible pigment state more directly than progressive darkening among flowers that are already pigmented. We therefore focus the directional test on the broadly distributed, directly documented focal pollinators *B. ardens* and *B. diversus*. Montane and alpine Bombus species are not pooled into the primary availability metric because their niches overlap the same high-elevation geography in which pigmented flowers are common; they instead provide a guardrail against mistaking shared mountain biogeography for a pollinator mechanism.

The broad natural template is also ecologically important because it defines what should count as exceptional. Without such a reference, a locally unusual colour state can be interpreted too readily as evidence of a new process. A large fitted residual is not automatically a biological anomaly, because residual magnitude also reflects model uncertainty, leverage and sampling geometry. This distinction is especially relevant in *C. punctata*, which is cultivated ornamentally and may therefore experience planting, escape or introgression in addition to natural environmental and biotic processes. Human influence is consequently not treated as a competing national predictor. We first ask whether a locally discordant colour configuration is unusual relative to repeated natural predictive maps, and only then examine whether independently defined candidates occupy distinctive human context. This final layer broadens the integrated framework from natural trait biogeography to the question of when human activity may perturb an otherwise spatially structured phenotype.

These questions are therefore linked by ecological necessity rather than assembled as parallel analyses. Quantitative image phenotyping makes the national environmental–spatial template possible; that template reveals why same-scale Bombus overlap is difficult to interpret and motivates a local boundary test; and the same template supplies the predictive reference needed to calibrate local departures before human context is considered. We ask: (1) what broad environmental and spatial structure organizes pigmentation state and conditional visible intensity across Japan; (2) within that template, whether the sharpest nearby white–pigmented transitions align directionally with availability of focal bumblebee pollinators; and (3) whether locally discordant pigmented populations are more frequent than expected under the broad natural model and, once defined independently, occupy distinctive human context. By integrating these layers without forcing them into one scale, we aim to explain not only where flower-colour variation occurs, but how different ecological processes can be distinguished within the same geographical mosaic.

'''

text = text[:start] + intro + text[end:]

old_aim = '**Aim:** Range-wide trait studies often combine coarse phenotypes with predictors that share broad geography, obscuring local biotic associations. We asked whether a quantitative flower-colour polymorphism could be resolved hierarchically by changing spatial scale and comparison unit with each ecological question.'
new_aim = '**Aim:** Geographical trait variation matters because it can mediate local adaptation and species interactions, yet abiotic, biotic, historical and human processes often share the same spatial structure. We asked whether a quantitative flower-colour polymorphism could be resolved through an integrated design that changes spatial scale and comparison unit with each ecological question.'
if old_aim not in text:
    raise SystemExit('Expected old Aim text not found')
text = text.replace(old_aim, new_aim, 1)

old_concl = '**Main conclusions:** Broad environment and space define the principal flower-colour template; any pollinator contribution appears, at most, highly local and concerns pigmentation state rather than colour intensity; and visually unusual populations should not automatically be treated as anthropogenic anomalies. Repurposed recreational imagery can support quantitative trait biogeography when sampling frame, trait construction and inferential scale are explicit.'
new_concl = '**Main conclusions:** Broad environment and space define the principal flower-colour template; any pollinator contribution appears, at most, highly local and concerns pigmentation state rather than colour intensity; and visually unusual populations should not automatically be treated as anthropogenic anomalies. The study shows why integrative trait biogeography must connect, rather than collapse, processes operating at different scales, and how repurposed recreational imagery can make that integration possible.'
if old_concl not in text:
    raise SystemExit('Expected old Main conclusions text not found')
text = text.replace(old_concl, new_concl, 1)

ref = 'Westerband, A. C., Funk, J. L., & Barton, K. E. (2021). Intraspecific trait variation in plants: a renewed focus on its role in ecological processes. *Annals of Botany*, 127, 397-410. https://doi.org/10.1093/aob/mcab011\n\n'
if 'Westerband, A. C.' not in text:
    marker = 'van der Kooi, C. J., Elzenga, J. T. M., Staal, M., & Stavenga, D. G. (2016).'
    pos = text.index(marker)
    text = text[:pos] + ref + text[pos:]

path.write_text(text, encoding='utf-8')
print('Rewrote JBI background around ecological significance and cross-scale integration.')
